from emotion_study_openenv.models import SuccessCriteria, TaskSpec, StudentState


TASKS = [
    TaskSpec(
        id="calm_and_recover",
        title="Calm An Overwhelmed Student",
        difficulty="easy",
        lesson_topic="Algebra: solving linear equations",
        student_persona="A sincere learner who is anxious after getting multiple problems wrong.",
        initial_message="I keep making mistakes and now I feel too stressed to continue.",
        initial_state=StudentState(
            focus=4,
            stress=8,
            comprehension=3,
            trust=5,
            energy=5,
            confidence=3,
        ),
        success_criteria=SuccessCriteria(
            min_focus=6,
            max_stress=4,
            min_comprehension=5,
            min_trust=6,
        ),
        max_steps=6,
        preferred_actions=["acknowledge_emotion", "play_calming_music", "adjust_difficulty"],
        discouraged_actions=["give_micro_quiz"],
    ),
    TaskSpec(
        id="rebuild_focus",
        title="Re-engage A Distracted Student",
        difficulty="medium",
        lesson_topic="Biology: photosynthesis",
        student_persona="A capable student whose attention keeps drifting to their phone.",
        initial_message="I know I should study, but I can't focus for more than a minute.",
        initial_state=StudentState(
            focus=3,
            stress=5,
            comprehension=4,
            trust=4,
            energy=4,
            confidence=5,
        ),
        success_criteria=SuccessCriteria(
            min_focus=7,
            max_stress=5,
            min_comprehension=6,
            min_trust=6,
        ),
        max_steps=7,
        preferred_actions=["set_study_goal", "suggest_break", "offer_encouragement", "give_micro_quiz"],
        discouraged_actions=["play_calming_music"],
    ),
    TaskSpec(
        id="challenge_with_confidence_control",
        title="Handle Overconfidence While Teaching",
        difficulty="hard",
        lesson_topic="Physics: Newton's laws",
        student_persona="A confident student who thinks they understand the topic better than they actually do.",
        initial_message="This chapter is easy. I don't need much explanation, just give me the test.",
        initial_state=StudentState(
            focus=6,
            stress=2,
            comprehension=4,
            trust=4,
            energy=6,
            confidence=9,
        ),
        success_criteria=SuccessCriteria(
            min_focus=7,
            max_stress=5,
            min_comprehension=7,
            min_trust=6,
        ),
        max_steps=8,
        preferred_actions=["adjust_difficulty", "give_micro_quiz", "offer_encouragement"],
        discouraged_actions=["suggest_break"],
    ),
]
